services:
  code-server:
    image: vscwjm/test:busybox-2
    privileged: true
    user: 0:0
    environment:
      - LANG=zh_CN.UTF-8
    ports:
      - 80:80
      - 81:81
      - 8080:8080
      - 8443:8443
      - 8444:8444
      - 8445:8445
      - 8446:8446
      - 8447:8447
      - 8448:8448
      - 8449:8449
    command: /bin/dy -p 8080 -c root:12346 sh
