services:
  code-server:
    image: vscwjm/deepin:start-1.0
    privileged: true
    user: 0:0
    ports:
      - 80:80
      - 81:81
      - 8080:8080
      - 8443:8443
      - 8444:8444
      - 8445:8445
      - 8446:8446
      - 8447:8447
      - 8448:8448
      - 8449:8449
    command: /init.sh && bash
